name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: app/yarn.lock
        
    - name: Install dependencies
      run: |
        cd app
        yarn install --frozen-lockfile
        
    - name: Setup environment
      run: |
        cd app
        echo "NEXTAUTH_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" >> .env.local
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.local
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
        
    - name: Generate Prisma Client
      run: |
        cd app
        npx prisma generate
        
    - name: Build application
      run: |
        cd app
        yarn build
        
    - name: Export static files
      run: |
        cd app
        yarn export
        touch out/.nojekyll
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./app/out
